### ISSUE TITLE
Why does a uni-typed language need optics?

### ISSUE THREAD

**Issue by michalrus** [flunc/optics#1]
:smiling_imp:

**Comment by michalrus** [comment]
:sweat

**Comment by scott-christopher** [comment]
The main benefit is the same as with a statically typed language: working with immutable/persistent data types. Unless I've misunderstood your question, the benefit of a static type system is unrelated (at least directly) to the use of composable lenses, prisms, traversals and isos.

I'm going to close this off, but feel free to reopen if I haven't answered your question.
